title: The Inquisitive Programmer
author: Daniel J. Rollins
description: >
    Inquisitive programmer spelunking through C and C++,
    systems programming and games development.
url: "http://www.djrollins.com"
baseurl: "" # the subpath of your site, e.g. /blog

ga-tracking-id: UA-84655627-1
permalink: pretty

markdown: kramdown

socials:
    github:
        fa: "fa-github"
        color: "#333333"
        url: "http://github.com/djrollins"
    twitter:
        fa: "fa-twitter"
        color: "#4099FF"
        url: "http://twitter.com/DanielJRollins"
    stack-overflow:
        fa: "fa-stack-overflow"
        color: "#F48024"
        url: "http://stackoverflow.com/users/2996594/djrollins"
    linkedin:
        fa: "fa-linkedin"
        color: "#1A85BC"
        url: "https://www.linkedin.com/in/djrollins"
    email:
        fa: "fa-envelope"
        color: "#77CAC1"
        url: "mailto:website@djrollins.com"

gems:
    - jekyll-sitemap
